name: marvel
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.1

  crypto: ^3.0.2

  cupertino_icons: ^1.0.2

  dartz: ^0.10.1

  dio: ^4.0.6

  equatable: ^2.0.3

  flutter_bloc: ^8.0.1
  
  flutter_dotenv: ^5.0.2

  flutter_staggered_animations: "^1.0.0"

  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  bloc_test: ^9.0.3

  build_runner:

  faker: ^2.0.0

  http_mock_adapter: ^0.3.2

  mockito: ^5.1.0

  network_image_mock: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
  
  fonts:
    - family: Marvel
      fonts:
        - asset: assets/fonts/Marvel.ttf
